//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public int IDMed { get; set; }
        public string NameMed { get; set; }
        public string Manufacturers { get; set; }
        public string Manufacturer_country { get; set; }
        public double PriceMed { get; set; }
        public string Image { get; set; }
    }
}
